ng-project.admin.web/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using ng_project.Entities;
using ng_project.Models;
using ng_project.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ng_project.admin.web.Controllers
{
	[Authorize]
	public class ProjectController : Controller
	{
		public ProjectController(IProjectService projectService,
			IProjectTypeService projectTypeService,
			IProjectSubTypeService projectSubTypeService,
			IRolesService rolesService,
			INgMainService NgProjectService)
		{
			this.projectService = projectService;
			this.projectTypeService = projectTypeService;
			this.projectSubTypeService = projectSubTypeService;
			this.rolesService = rolesService;
			this.NgProjectService = NgProjectService;
		}
		private IProjectService projectService;
		private IProjectTypeService projectTypeService;
		private IProjectSubTypeService projectSubTypeService;
		private IRolesService rolesService;
		private INgMainService NgProjectService;
		public IActionResult All()
		{
			var model = projectService.FindAll();
			return View();
		}
		[HttpGet]
		public HtmlString GetRoles()
		{
			var roles = rolesService.FindAll();
			var sb = new StringBuilder();
			sb.Append("<div class=\"input-group\">");
			sb.Append(@"<select class=""form-control"" id=""select-roles"" name=""select-roles"">");
			foreach (var role in roles)
			{
				sb.Append($"<option value=\"{role.Id}\">{role.Name}</option >");
			}
			sb.Append("</select>");
			sb.Append(@"<span class=""input-group-text add-skills-btn BlueThemeColor AddRole"">
		Добавить
	</span>");
			sb.Append("</div>");
			return new HtmlString(sb.ToString());
		}
		[HttpGet]
		public HtmlString SetRoles(int roleId, int projectTypeId)
		{
			var lastRole = NgProjectService.FindByFunc<ProjectTypeRoles, int>(t => t.RolesId == roleId && t.ProjectTypeId == projectTypeId);
			if (lastRole != null)
			{
				return new HtmlString("");
			}
			NgProjectService.Add<ProjectTypeRoles, int>(new ProjectTypeRoles()
			{
				RolesId = roleId,
				ProjectTypeId = projectTypeId
			});
			var sb = new StringBuilder();
			var role = rolesService.Find(t=> t.Id == roleId);
			sb.Append($"<span class=\"participant-skill-item\">{role.Name}</span>");
			return new HtmlString(sb.ToString());
		}
		[HttpGet]
		public IActionResult EditProjectType(int id)
		{
			var model = projectTypeService
				.Include(t => t.ProjectSubType)
				.Include(t => t.ProjectTypesRoles)
				.Find(t => t.Id == id);

			model.ProjectSubType = projectSubTypeService.FindAll(t => t.ProjectTypeId == model.Id).ToList();
			return View(model);
		}
		[HttpPost]
		public IActionResult EditProjectType(ProjectType projectType)
		{
			projectTypeService.Save(projectType);
			return RedirectToAction("AllProjectType");
		}
		[HttpGet]
		public IActionResult AllProjectType()
		{
			var model = projectTypeService.FindAll();
			return View(model);
		}
		[HttpGet]
		public IActionResult AllProjectSubType()
		{
			var model = projectSubTypeService.FindAll();
			return View(model);
		}
		[HttpGet]
		public IActionResult EditProjectSubType(int id)
		{
			var model = projectSubTypeService.Find(t=> t.Id == id);
			model.ProjectType = projectTypeService.Find(t=> t.Id == model.ProjectTypeId);
			return View(model);
		}
		[HttpPost]
		public IActionResult EditProjectSubType(ProjectSubType projectSubType)
		{
			projectSubTypeService.Save(projectSubType);
			return RedirectToAction("AllProjectSubType");
		}
		[HttpGet]
		public IActionResult AddProjectType()
		{
			return View();
		}
		[HttpPost]
		public IActionResult AddProjectType(ProjectType projectType)
		{
			projectTypeService.Add(projectType);
			return RedirectToAction("AllProjectType");
		}
		[HttpGet]
		public HtmlString AddNewSubType(string subTypeName, int index, int projectTypeId)
		{
			var newIndex = projectSubTypeService.Add(new ProjectSubType()
			{
				Name = subTypeName,
				ProjectTypeId= projectTypeId
			});
			return new HtmlString(string.Format(@"
				<input type=""hidden"" name=""ProjectSubType[{1}].Id"" value=""{2}"" />
				<input type=""hidden"" name=""ProjectSubType[{1}].Name"" value=""{0}"" />
				<span class=""participant-skill-item"">{0}</span>", subTypeName, index, newIndex));
		}
	}
}

ng-project.admin.web/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ng_project.Entities;
using ng_project.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ng_project.admin.web.Controllers
{
	[Authorize]
	public class RolesController : Controller
	{
		public RolesController(IRolesService rolesService)
		{
			this.rolesService = rolesService;
		}
		private IRolesService rolesService;
		public IActionResult Index()
		{
			return View();
		}
		public IActionResult All()
		{
			var model = rolesService.FindAll();
			return View(model);
		}
		[HttpGet]
		public IActionResult Add()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Add(Roles roles)
		{
			rolesService.Add(roles);
			return RedirectToAction("All");
		}
		[HttpGet]
		public IActionResult Edit(int id)
		{
			var model = rolesService.FindById(id);
			return View(model);
		}
		[HttpPost]
		public IActionResult Edit(Roles roles)
		{
			rolesService.Save(roles);
			return RedirectToAction("All");
		}
	}
}

ng-project.admin.web/Controllers/SkillController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ng_project.Entities;
using ng_project.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ng_project.admin.web.Controllers
{
	[Authorize]
	public class SkillController : Controller
	{
		public SkillController(ISkillService skillService)
		{
			this.skillService = skillService;
		}
		private ISkillService skillService;
		public IActionResult All()
		{
			var model = skillService.FindAll();
			return View(model);
		}
		
		[HttpPost]
		public IActionResult Add(Skill skill)
		{
			skillService.Add(skill);
			return RedirectToAction("All");
		}
		[HttpGet]
		public IActionResult Add()
		{
			return View();
		}
	}
}

ng-project.admin.web/Controllers/UserController.cs
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using ng_project.Entities;
using ng_project.EntityExpressions;
using ng_project.Models;
using ng_project.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ng_project.admin.web.Controllers
{
	public class UserController : Controller
	{
		public UserController(IUserService userService
			, IRolesService rolesService
			, IWorkerService workerService
			, ISubscribeService subscribeService
			, IProjectService projectService)
		{
			this.userService = userService;
			this.rolesService = rolesService;
			this.workerService = workerService;
			this.subscribeService = subscribeService;
			this.projectService = projectService;
		}
		private IUserService userService;
		private IRolesService rolesService;
		private IWorkerService workerService;
		private ISubscribeService subscribeService;
		private IProjectService projectService;
		[HttpGet]
		public string[] GetRolesItems()
		{
			var roles = rolesService.FindAll().Select(t=> t.Name).ToArray();
			return roles;
		}
		public IActionResult DeleteUser(int id)
		{
			var worker = workerService.Find(t => t.UserId == id);
			var sub = subscribeService.Find(t => t.UserId == id);
			if(worker != null)
			{
				workerService.Delete(worker.Id);
			}
			if(sub != null)
			{
				var projects = projectService.FindAll(t => t.UserId == id);
				foreach(var proj in projects)
				{
					projectService.RemoveLink(new ProjectSubscriber()
					{ 
						ProjectsId = proj.Id,
						SubscribersId = sub.Id
					});
				}
				subscribeService.Delete(sub.Id);
			}
			userService.Delete(id);
			return RedirectToAction("All");
		}
		[HttpPost]
		public HtmlString AddNewRole(string roleName, int index)
		{
			var model = rolesService.Find(t => t.Name == roleName);
			int modelId = 0;
			if(model == null)
			{
				modelId = rolesService.Add(new Roles()
				{
					Name = roleName
				});
				return new HtmlString(string.Format(@"
<input type=""hidden"" name=""Roles[{0}].Id"" value=""{1}"" />
<input type=""hidden"" name=""Roles[{0}].Name"" value=""{2}"" />
<span class=""participant-skill-item"">{2}</span>
", index, modelId, roleName));
			}
			return new HtmlString(string.Format(@"
<input type=""hidden"" name=""Roles[{0}].Id"" value=""{1}"" />
<input type=""hidden"" name=""Roles[{0}].Name"" value=""{2}"" />
<span class=""participant-skill-item"">{2}</span>
", index, model.Id, model.Name));
		}
		[HttpGet]
		public IActionResult All()
		{
			var model = userService.FindAll();
			return View(model);
		}
		[HttpGet]
		public IActionResult Edit(int id)
		{
			var model = userService
				.Include(t => t.Projects)
				.Include(t => t.Creator)
				.Include(t => t.Email)
				.Find(t=> t.Id == id);
			return View(model);
		}
		[HttpPost]
		public IActionResult Edit(User user)
		{
			userService.Save(user);
			return RedirectToAction("All");
		}
	}
}

ng-project.admin.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - ng_project.admin.web</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="~/css/Themes.css" />
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ng_project.admin.web</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<ul class="navbar-nav flex-grow-1">

						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Пользователи</a>
							<div class="dropdown-menu">
								<a class="dropdown-item" asp-area="" asp-action="All" asp-controller="User">Все</a>
								<a class="dropdown-item" href="#">Участники</a>
								<a class="dropdown-item" href="#">Создатели</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="#">Создать пользователя</a>
							</div>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Проекты</a>
							<div class="dropdown-menu">
								<a class="dropdown-item" asp-area="" asp-action="All" asp-controller="Project">Все</a>
								<a class="dropdown-item" asp-area="" asp-action="AllProjectType" asp-controller="Project">Все типы проектов</a>
								<a class="dropdown-item" asp-area="" asp-action="AllProjectSubType" asp-controller="Project">Все под типы проектов</a>
								<a class="dropdown-item" asp-area="" asp-action="AddProjectType" asp-controller="Project">Создать тип проекта</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="#">Создать проект</a>
							</div>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Навыки</a>
							<div class="dropdown-menu">
								<a class="dropdown-item" asp-area="" asp-controller="Skill" asp-action="All">Все</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" asp-area="" asp-controller="Skill" asp-action="Add">Создать навык</a>
							</div>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Роли</a>
							<div class="dropdown-menu">
								<a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="All">Все</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="Add">Создать роль</a>
							</div>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Настройки</a>
						</li>
						@if (User.Identity.IsAuthenticated)
						{
							<li class="nav-item">
								<a asp-action="Profile" asp-controller="User" class="nav-link">@("Здравствуйте " + User.Identity.Name + "!")</a>
							</li>
							<li class="nav-item">
								<a asp-action="LogOut" asp-controller="Account" class="btn btn-info">Выйти</a>
							</li>
						}
						else
						{
							<li class="nav-item">
								<a asp-action="Registration" asp-controller="Account" class="btn btn-info mr-2">Регистрация</a>
							</li>
							<li class="nav-item">
								<a asp-action="Login" asp-controller="Account" class="btn btn-info">Выполнить вход</a>
							</li>
						}

					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2021 - ng_project.admin.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	@*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
	<script>

		function ShowLoader() {
			$('.loader-main-block .loader-bacdrop').show();
			$('.loader-main-block .loader-block').show();
		}
		function HideLoader() {
			$('.loader-main-block .loader-bacdrop').hide();
			$('.loader-main-block .loader-block').hide();
		}
	</script>
</body>
</html>