ng-project.web/Controllers/ParticipantController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ng_project.Entities;
using ng_project.Services;
using ng_project.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ng_project.web.Controllers
{
	/// <summary>
	/// Контроллер участников
	/// </summary>
	public class ParticipantController : Controller
	{
		public IWorkerService ParticipantService { get; set; }
		public IProjectService ProjectService { get; set; }
		public ISkillService SkillService { get; set; }
		public IUserService UserService { get; set; }
		public INotifyService NotifyService { get; set; }

		[HttpPost]
		public IActionResult SendBecome(int ProjectId, string SendText)
		{
			var project = ProjectService.FindById(ProjectId);
			var user = UserService.Find(t => t.login == User.Identity.Name);
			NotifyService.Add(new Notify()
			{
				IsReading = false,
				Message = SendText,
				ProjectId = ProjectId,
				SendDate = DateTime.Now,
				RecipientId = project.UserId,
				SenderId = user.Id
			});
			return RedirectToAction("All");
		}

		/// <summary>
		/// Получить навыки участника
		/// </summary>
		/// <returns></returns>
		[HttpGet]
		public string[] GetSkillItems()
		{
			var skills = SkillService.FindAll().Select(t => t.Name).ToArray();
			return skills;
		}
		
		/// <summary>
		/// Все участники
		/// </summary>
		/// <returns></returns>
		public IActionResult All()
		{
			var model = ParticipantService
				.Include(t => t.SkillWorkers)
				.Include(t => t.Projects)
				.Include(t => t.User)
				.FindAll();
			return View(model.ToList());
		}

		/// <summary>
		/// Получить список 
		/// </summary>
		/// <param name="id"></param>
		/// <returns></returns>
		[HttpGet]
		public IActionResult Index(int id)
		{
			var model = UserService
				.Include(t => t.Email)
				.Include(t => t.Worker)
				.Include(t => t.Creator)
				.Include(t => t.Projects)
				.Include(t => t.RolesUsers)
				.FindAll(t => t.RolesUsers.Select(s => s.RolesId).Contains(id));
			return View(model.ToList());
		}
		[HttpGet]
		public IActionResult Info(int id)
		{
			var participant = ParticipantService
				.Include(t => t.User)
				.Include(t=> t.SkillWorkers)
				.FindById(id);
			return View(participant);
		}
		[HttpPost]
		public void RemoveSkill(int id)
		{
			SkillService.Delete(id);
		}
	}
}

ng-project.web/Views/Shared/Participant/_Roles.cshtml
@using ng_project.Entities;
@inject ng_project.Services.IRolesService roleService;

@model ProjectType;

@foreach (var role in Model.Roles)
{
	var roleInfo = roleService.Include(t => t.RolesUsers).FindById(role.Id);

	<div class="col-4" onclick="window.location.href='@(Url.Action("Index","Participant",new { id=role.Id }))'">
		<div class="participant-item">
			<div class="opacityBackground">
				<div class="block BlueTheme">
					<div class="name">
						@(roleInfo.Name)
					</div>
					<div class="count">
						количество участников: @(roleInfo.Users?.Count)
					</div>
				</div>
			</div>

			<div class="description">
				Отвечают за написание кода
			</div>
		</div>
	</div>
}

ng-project.web/Views/Shared/Participant/_SendRequest.cshtml
@using ng_project.Services;
@using ng_project.Entities;
@inject IProjectService ProjectService;

@{ 
	var projectList = ProjectService.Include(t => t.User).FindAll(t => t.User.login == User.Identity.Name);
	var selectProject = new SelectList(projectList, "Id", "Name");
}

<form method="post" asp-action="SendBecome" asp-controller="Participant">
	<div class="modal-dialog ">
		<div class="modal-content OrangeTheme">
			<div class="modal-header">
				<h5 class="modal-title" id="staticBackdropLabel">Выбрать проект</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<label>Проект</label>
				@Html.DropDownList("ProjectId", selectProject, new { @class = "form-control" })
				<label>Сообщение</label>
				<div class="text">
					<textarea placeholder="Введите текст ..." name="SendText" style="width:100%;border-radius:0.5em;padding:1em;"></textarea>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
				<button type="submit" class="btn btn-primary">Выбрать</button>
			</div>
		</div>
	</div>
</form>