ng-project.web/Controllers/NotifyController.cs
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using ng_project.Entities;
using ng_project.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ng_project.web.Controllers
{
	/// <summary>
	/// Контроллер для работы с уведомлениями
	/// </summary>
	public class NotifyController : Controller
	{
		public INotifyService NotifyService { get; set; }
		public IProjectService ProjectService { get; set; }
		public IUserService UserService { get; set; }
		public IActionResult Index()
		{
			var user = UserService.Find(t => t.login == User.Identity.Name);
			var model = NotifyService
				.Include(t=> t.Recipient)
				.Include(t=> t.Sender)
				.Include(t=> t.Project)
				.FindAll(t => t.RecipientId == user.Id);
			return View(model);
		}
		public IActionResult GetProject(int notifyId)
		{
			if(notifyId == 0)
				return PartialView("Notify/NotProject");

			var model = NotifyService
				.Include(t => t.Recipient)
				.Include(t => t.Sender)
				.Include(t => t.Project)
				.FindById(notifyId);

			return PartialView("Notify/Message", model);
		}
		public IActionResult SetResult(int id, bool isSuccess)
		{
			var model = NotifyService
				.Include(t => t.Recipient)
				.Include(t => t.Sender)
				.Include(t => t.Project)
				.FindById(id);
			
			if (isSuccess)
			{
				var sender = UserService.Include(t => t.Worker).FindById(model.SenderId);
				ProjectService.AddParticipant(model.ProjectId, sender.Worker.Id);
			}

			NotifyService.Delete(id);
			return RedirectToAction("Index");
		}
	}
}

ng-project.web/Views/Notify/Index.cshtml
@using ng_project.Entities;

@model List<Notify>;

<link rel="stylesheet" href="~/css/Notify.css" />

<div class="container">
	<div class="row">
		<div class="col-3">
			<div class="request-list">
				@foreach (var notify in Model)
				{
					<div class="request-item mt-2">
						<input type="hidden" value="@(notify.Id)" class="notify_id"/>
						<div class="name">
							@($"{notify.Sender.LastName} {notify.Sender.FirstName}")
						</div>
						<div class="date">
							@(notify.SendDate.ToLongDateString())
						</div>
					</div>
				}

			</div>
		</div>
		<div class="col-9">
			<div class="message-item">
			</div>
		</div>
	</div>
</div>


<script>
	$(document).ready(function ()
	{
		$('.request-item:first').addClass("select");
		$.ajax(
		{
			url: '@(Url.Action("GetProject","Notify"))',
			type: 'GET',
			data: { notifyId:@(Model.FirstOrDefault()?.Id??0)},
			success: function (data) {
				$('.message-item').empty();
				$('.message-item').append(data);
			}
		})
		$('.request-item').bind("click", function () {
			$('.request-item').removeClass("select");
			debugger;
			var notifyid = $(this).children(".notify_id")[0].value;
			$(this).addClass("select");
			SetMessage(notifyid);

		})
	})

	function SetMessage(notifyid) {
		$.ajax(
		{
			url: '@(Url.Action("GetProject","Notify"))',
			type: 'GET',
			data: { notifyId: notifyid},
			success: function (data) {
				$('.message-item').empty();
				$('.message-item').append(data);
			}
		})
	}
</script>